---
  CinderVolumes.create_volume_backup:
    -
      args:
        size: 1
        do_delete: True
        create_volume_kwargs: {}
        create_backup_kwargs: {}
      runner:
        type: "constant"
        times: 2
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        roles:
          - "Member"
