---
  SaharaClusters.create_scale_delete_cluster:
    -
      args:
        master_flavor:
         name: "m1.large"
        worker_flavor:
         name: "m1.medium"
        workers_count: 3
        deltas:
          - 1
          - -1
          - 1
          - -1
        plugin_name: "vanilla"
        hadoop_version: "2.3.0"
        auto_security_group: True
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        sahara_image:
          image_url: "http://sahara-files.mirantis.com/sahara-icehouse-vanilla-2.3.0-ubuntu-13.10.qcow2"
          username: "ubuntu"
          plugin_name: "vanilla"
          hadoop_version: "2.3.0"
        network: {}
