---
  SaharaJob.create_launch_job_sequence:
    -
      args:
        jobs:
          -
            job_type: "Java"
            configs:
              configs:
                edp.java.main_class: "org.apache.hadoop.fs.TestDFSIO"
              args:
               - "-write"
               - "-nrFiles"
               - "10"
               - "-fileSize"
               - "100"
          -
            job_type: "Java"
            configs:
              configs:
                edp.java.main_class: "org.apache.hadoop.fs.TestDFSIO"
              args:
               - "-read"
               - "-nrFiles"
               - "10"
               - "-fileSize"
               - "100"
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        sahara_image:
          image_url: "http://sahara-files.mirantis.com/mos70/sahara-kilo-vanilla-2.6.0-ubuntu-14.04.qcow2"
          username: "ubuntu"
          plugin_name: "vanilla"
          hadoop_version: "2.6.0"
        sahara_job_binaries:
          libs:
            -
              name: "tests.jar"
              download_url: "http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/2.6.0/hadoop-hdfs-2.6.0-tests.jar"
        sahara_cluster:
          master_flavor_id: "4"
          worker_flavor_id: "3"
          workers_count: 3
          plugin_name: "vanilla"
          hadoop_version: "2.6.0"
          auto_security_group: True
        network: {}
