---
  ManilaShares.list_shares:
    -
      args:
        detailed: True
      runner:
        type: "constant"
        times: 10
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
