---
  DesignateBasic.list_recordsets:
    -
      args:
        zone_id: <uuid>
      runner:
        type: "constant"
        times: 3
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
