---
  IronicNodes.create_and_delete_node:
    -
      args:
        driver: "pxe_ssh"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 5
          users_per_tenant: 1
