---
  HeatStacks.create_and_delete_stack:
    -
      args:
        template_path: "templates/resource_group_with_constraint.yaml.template"
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2