{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.boot_and_bounce_server:
    -
      args:
        flavor:
            name: "{{flavor_name}}"
        image:
            name: "^cirros.*uec$"
        force_delete: false
        actions:
          -
            hard_reboot: 1
          -
            soft_reboot: 1
          -
            stop_start: 1
          -
            rescue_unrescue: 1
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 2
