{% set flavor_name = flavor_name or "m1.tiny" %}
---
NovaServers.boot_server_attach_created_volume_and_live_migrate:
- args:
    flavor:
      name: "{{flavor_name}}"
    image:
      name: "^cirros.*uec$"
    size: 10
    block_migration: false
  runner:
    type: constant
    times: 5
    concurrency: 1
  context:
    users:
      tenants: 2
      users_per_tenant: 2
