{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.boot_and_delete_multiple_servers:
    -
      args:
        image:
          name: "^cirros.*uec$"
        flavor:
          name: "{{flavor_name}}"
        count: 5
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
