{% set flavor_name = flavor_name or "m1.tiny" %}
---
  NovaServers.list_servers:
    -
      args:
        detailed: True
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        servers:
          flavor:
              name: "{{flavor_name}}"
          image:
              name: "^cirros.*uec$"
          servers_per_tenant: 2
