---
  NeutronLoadbalancerV1.create_and_list_healthmonitors:
    -
      args:
        healthmonitor_create_args: {}
      runner:
        type: "constant"
        times: 100
        concurrency: 10
      context:
        users:
          tenants: 5
          users_per_tenant: 2
        quotas:
          neutron:
            health_monitor: -1
