---
  NeutronNetworks.create_and_delete_floating_ips:
    -
      args:
        floating_network: "public"
        floating_ip_args: {}
      runner:
        type: "constant"
        times: 10
        concurrency: 5
      context:
        users:
          tenants: 2
          users_per_tenant: 3
        quotas:
          neutron:
            floatingip: -1
